server.port: 7001
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

jwt.expiration: 1800000
jwt.secret: wc1S3CR3TK3YB4S364TH4TI2SUp3RL0NG
jwt.refreshexpiration: 86400000
jwt.passwordtokenexpiration: 900000

spring.datasource:
#  url: jdbc:mysql://localhost:3306/WondaCabinetIncDb?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
  url: jdbc:mysql://b2b521d4213c6e:af23b392@us-cdbr-east-05.cleardb.net/heroku_83263710f1fb513?reconnect=true/WondaCabinetIncDb?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.wondacabinetinc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql/WondaCabinetIncDb
    username: user
    password: pwd
    initialization-mode: always

    jpa:
      hibernate:
        ddl-auto: none

spring.datasource.hikari.initializationFailTimeout: 60000


server.port: 8080

